"""``docsweep init`` — 初回ウィザード（UX W1 / P1）。

config が無いときは roots / lang / AI ヒントを書いて ~/.docsweep/config.yaml を作る。
既にあるときは差分確認のみ（破壊的上書きしない）。``--yes`` で非対話。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .config import GLOBAL_CONFIG_PATH


@dataclass
class InitResult:
    created: bool
    config_path: str
    message: str
    next_steps: list[str] = field(default_factory=list)
    config_preview: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "created": self.created,
            "config_path": self.config_path,
            "message": self.message,
            "next_steps": list(self.next_steps),
            "config_preview": dict(self.config_preview),
        }


def _default_root() -> str:
    # カレントを初期 root に（ユーザーがいつでも直せる）
    return str(Path.cwd().resolve())


def _build_config_body(
    *,
    root: str,
    lang: str,
    agent: str,
) -> dict[str, Any]:
    body: dict[str, Any] = {
        "roots": [root],
        "lang": lang if lang in ("ja", "en") else "ja",
        "projects": {
            "search_paths": [root],
        },
    }
    # agent はヒントコメント用（実行時は inject で使う）
    if agent and agent != "none":
        body["init"] = {"agent": agent}
    return body


def run_init(
    *,
    yes: bool = False,
    root: str | None = None,
    lang: str = "ja",
    agent: str = "claude",
    global_path: Path | None = None,
    force: bool = False,
) -> InitResult:
    """init を実行。既存 config は force 無しでは作らない。"""
    path = (global_path or GLOBAL_CONFIG_PATH).expanduser()
    next_steps = [
        "python -m docsweep index-sync",
        "python -m docsweep doctor",
        "python -m docsweep brief   # または  python -m docsweep serve",
    ]
    if agent and agent != "none":
        next_steps.insert(1, "python -m docsweep inject --global")

    if path.is_file() and not force:
        try:
            existing = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except Exception:  # noqa: BLE001
            existing = {}
        return InitResult(
            created=False,
            config_path=str(path),
            message=f"既に config があります: {path}（上書きしない。--force で再生成）",
            next_steps=next_steps,
            config_preview=existing if isinstance(existing, dict) else {},
        )

    root_s = root or _default_root()
    if not yes and root is None:
        # 非対話ライブラリなし: 呼び出し側が interactive で埋める想定。
        # ここは API として root 必須相当。未指定なら cwd。
        pass

    body = _build_config_body(root=root_s, lang=lang, agent=agent)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "# docsweep config (generated by `docsweep init`)\n"
        "# edit roots / lang freely.\n"
        + yaml.safe_dump(body, allow_unicode=True, sort_keys=False)
    )
    path.write_text(text, encoding="utf-8")
    return InitResult(
        created=True,
        config_path=str(path),
        message=f"config を作成しました: {path}",
        next_steps=next_steps,
        config_preview=body,
    )


def interactive_prompts() -> dict[str, str]:
    """標準入力から 3 問。非 TTY では既定値。"""
    import sys

    defaults = {
        "root": _default_root(),
        "lang": "ja",
        "agent": "claude",
    }
    if not (sys.stdin.isatty() and sys.stdout.isatty()):
        return defaults

    def ask(prompt: str, default: str) -> str:
        try:
            raw = input(f"{prompt} [{default}]: ").strip()
        except EOFError:
            return default
        return raw or default

    root = ask("スキャン root（絶対パス推奨）", defaults["root"])
    lang = ask("言語 ja/en", defaults["lang"])
    agent = ask("AI ツール claude/codex/none", defaults["agent"])
    if lang not in ("ja", "en"):
        lang = "ja"
    if agent not in ("claude", "codex", "none"):
        agent = "claude"
    return {"root": root, "lang": lang, "agent": agent}
