"""注入（inject）と取り消し（eject）— C7。

各プロジェクトへ書き込むもの:
1. .docsweep.yaml（ツールが読む設定。states/preset）
2. CLAUDE.md / AGENTS.md の管理ブロック（AI が読む運用ルール文。マーカー内だけ書換）

- マーカー内だけ書き換え、外側のユーザー手書きは温存。再注入でユーザー編集を壊さない（冪等）。
- 手編集検出: 管理ブロック内が前回注入時と変わっていたら警告＋.bak バックアップしてから処理。
- マニフェスト ~/.docsweep/injected.json にどのプロジェクトへ注入したかを記録。
"""

from __future__ import annotations

import hashlib
import json
import os
import shlex
import subprocess
import sys
from dataclasses import dataclass, field, replace
from datetime import datetime
from pathlib import Path

import yaml

from .config import DEFAULT_DUE_OFFSET_DAYS, GLOBAL_CONFIG_PATH
from .presets import Preset, get_preset
from .states import StateModel

MARK_START = "<!-- docsweep:managed:start -->"
MARK_END = "<!-- docsweep:managed:end -->"
MANIFEST_PATH = Path.home() / ".docsweep" / "injected.json"
DEFAULT_TARGETS = ("CLAUDE.md", "AGENTS.md")

# グローバル注入をサポートする AI ツール。注入先パスは固定せず、各ツールの契約に従って動的解決する
# （Claude=単一ファイル / Codex=CODEX_HOME 相対＋override 優先）。未対応ツールは --global-target で明示。
SUPPORTED_GLOBAL_AGENTS = ("claude", "codex")

# docsweep が所有する中央導線ファイル。実体はここ 1 つに集約し、各ツールには最小フックだけ書く
# （Claude=@import 1 行で取り込み / Codex 等=@import 非対応のため本文をブロック展開）。
GUIDANCE_PATH = Path.home() / ".docsweep" / "guidance.md"
GUIDANCE_IMPORT = "~/.docsweep/guidance.md"  # Claude の @import 行（先頭 ~ は Claude が展開する）

# グローバル導線ブロック（generate_guidance_block の出力）の改訂版。文言を変えたら手で bump する。
# 注入時にマニフェストへ記録し UI が「どの版が入っているか」を表示する。
GUIDANCE_VERSION = "4"


def _shell_command(parts: list[str]) -> str:
    if os.name == "nt":
        return subprocess.list2cmdline(parts)
    return shlex.join(parts)


def docsweep_command(*args: str) -> str:
    """PATH に依存しない docsweep 起動コマンドを返す。

    通常の Python パッケージ実行では現在の Python 実行ファイルから ``-m docsweep`` を呼ぶ。
    PyInstaller 等の単体バイナリでは、そのバイナリ自体を絶対パスで呼ぶ。
    """
    exe = str(Path(sys.executable).resolve())
    if getattr(sys, "frozen", False):
        return _shell_command([exe, *args])
    return _shell_command([exe, "-m", "docsweep", *args])


def _codex_home() -> Path:
    """Codex のホーム。CODEX_HOME を尊重し、無ければ ~/.codex（公式仕様準拠）。"""
    return Path(os.environ.get("CODEX_HOME") or (Path.home() / ".codex"))


def resolve_global_target(agent: str = "claude", target: str | Path | None = None) -> Path:
    """グローバル注入先の絶対パスを解決する（明示 target 優先、無ければ agent ごとの契約で決定）。

    - claude: ``~/.claude/CLAUDE.md``（単一・常に読まれる）
    - codex : ``$CODEX_HOME/AGENTS.md``（既定 ``~/.codex/AGENTS.md``）。
      なお Codex は同階層に ``AGENTS.override.md`` があるとそちらを優先し AGENTS.md を無視するため、
      注入時に override の有無を検査して警告する（``_warn_if_shadowed``）。
    """
    if target:
        return Path(target).expanduser().resolve()
    if agent == "claude":
        return (Path.home() / ".claude" / "CLAUDE.md").resolve()
    if agent == "codex":
        return (_codex_home() / "AGENTS.md").resolve()
    raise ValueError(f"未知の agent: {agent}（claude / codex、または --global-target で明示）")


def _agent_uses_central(agent: str | None) -> bool:
    """中央 guidance.md を @import で参照する agent か（Claude のみ。Codex 等はインライン展開で参照しない）。"""
    return agent == "claude"


def _warn_if_shadowed(path: Path, result: InjectResult | EjectResult, agent: str = "codex") -> None:
    """Codex 系で同階層に AGENTS.override.md があると、注入先が読まれない旨を警告する。

    Claude は override の概念が無いので対象外。Codex は override を最優先し AGENTS.md/フォールバック
    （TEAM_GUIDE.md 等）を無視するため、注入先名を問わず override の存在で警告する。
    """
    if _agent_uses_central(agent):  # claude は対象外
        return
    if path.name != "AGENTS.override.md" and (path.parent / "AGENTS.override.md").is_file():
        result.warnings.append(
            f"同階層に AGENTS.override.md があります。Codex はこちらを優先し {path.name} を読みません。"
            " 導線を効かせるには override 側に取り込むか、--global-target で override を指定してください。"
        )


@dataclass
class InjectResult:
    project: str
    written: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    yaml_path: str | None = None


def _block_hash(inner: str) -> str:
    return hashlib.sha256(inner.strip().encode("utf-8")).hexdigest()[:16]


def _managed_note(eject_cmd: str, lang: str = "ja") -> str:
    """人間が「docsweep が付けた」と一目で分かる注記。最小フック（@import 1 行等）にも必ず添える。"""
    if lang == "en":
        return (
            f"<!-- ⚠ This block is auto-added and managed by docsweep inject. "
            f"Do not edit by hand; remove it with `{eject_cmd}`. -->"
        )
    return (
        f"<!-- ⚠ この内容は docsweep inject が自動追加・管理します。"
        f"手で編集せず `{eject_cmd}` で削除してください。 -->"
    )


def _hook_inner(body: str, eject_cmd: str, lang: str = "ja") -> str:
    """注記付きの最小フック本文（マーカーで包む前の inner）を作る。"""
    return _managed_note(eject_cmd, lang) + "\n" + body


def write_guidance_file(lang: str = "ja", *, dry_run: bool = False) -> Path:
    """docsweep 所有の中央導線ファイルを生成・再生成する（直接編集禁止の注記付き）。"""
    if lang == "en":
        header = (
            "<!-- This file is owned and auto-generated by docsweep. Do not edit directly"
            f" (regenerate with `{docsweep_command('inject', '--global')}` / "
            f"remove the reference with `{docsweep_command('eject', '--global')}`). -->"
        )
    else:
        header = (
            "<!-- このファイルは docsweep が所有・自動生成します。直接編集しないでください"
            f"（`{docsweep_command('inject', '--global')}` で再生成 / "
            f"`{docsweep_command('eject', '--global')}` で参照解除）。 -->"
        )
    content = header + "\n\n" + generate_guidance_block(lang) + "\n"
    if not dry_run:
        GUIDANCE_PATH.parent.mkdir(parents=True, exist_ok=True)
        GUIDANCE_PATH.write_text(content, encoding="utf-8")
    return GUIDANCE_PATH


def generate_label_block(sm: StateModel, lang: str = "ja", *, use_frontmatter: bool = False) -> str:
    """states から CLAUDE.md のラベル節（プロジェクト固有・状態モデル）を生成する。

    `.docsweep.yaml` の states から導出するためプロジェクトごとに変わる。グローバルには置かない。
    """
    en = lang == "en"
    watching_state = sm.by_key("watching")
    watching_label = watching_state.label(lang) if watching_state else ("Watching" if en else "様子見")
    done_label = sm.by_key("done").label(lang) if sm.by_key("done") else ("Done" if en else "完了")
    discarded_label = (
        sm.by_key("discarded").label(lang) if sm.by_key("discarded") else ("Discarded" if en else "廃止")
    )
    if en:
        lines: list[str] = [
            "## Status labels for AI work documents (managed by docsweep)",
            "",
            "This block is generated and synced by `docsweep inject`. Do not edit it by hand",
            f"(detach it first with `{docsweep_command('eject')}`). docsweep reads the label at the",
            "start of the H1 title, moves done/discarded files to `archive/`, and flags stale files for review.",
            "",
            "| internal state | label | auto archive |",
            "|---|---|---|",
        ]
    else:
        lines = [
            "## AI 作業ドキュメントのステータスラベル（docsweep 管理）",
            "",
            "このブロックは `docsweep inject` が生成・同期します。手で編集しないでください",
            f"（編集は `{docsweep_command('eject')}` で剥がしてから）。docsweep は H1 先頭のラベルを読み取り、",
            "完了/廃止を archive へ移送し、陳腐化を要判断フラグで可視化します。",
            "",
            "| 内部状態 | ラベル | 自動 archive |",
            "|---|---|---|",
        ]
    for st in sm.states:
        mark = "✓" if st.archive else "✗"
        note = "" if st.archive else ""
        if st.key == "watching":
            note = " (resting = protected)" if en else "（寝かせ中＝守る）"
        lines.append(f"| {st.key} | `[{st.label(lang)}]` | {mark}{note} |")
    if en:
        lines += [
            "",
            f"- `[{watching_label}]` means the file is resting for recurrence checks. **docsweep never auto-moves it**.",
            f"- Terminal states are manual decisions: mark `[{done_label}]` when finished, `[{discarded_label}]`"
            " when obsolete (quarantined into `archive/`, not deleted).",
        ]
        if use_frontmatter:
            lines += [
                "- You may also add `status: <internal state>` to the front matter"
                " (detection order: frontmatter > H1 > filename).",
            ]
    else:
        lines += [
            "",
            f"- `[{watching_label}]` は再発確認のため寝かせている状態。**docsweep は自動移送しない**。",
            f"- 終端は手の意思決定: 片付いたら `[{done_label}]`、陳腐化は `[{discarded_label}]`（削除ではなく archive へ隔離）。",
        ]
        if use_frontmatter:
            lines += [
                "- front matter に `status: <内部状態>` を併記してもよい（検出は frontmatter > H1 > filename）。",
            ]
    return "\n".join(lines)


def generate_due_block(lang: str = "ja") -> str:
    """対応期日（``due:``）ルール節を生成する（プロジェクト非依存・導線と一緒に配る）。

    文言は「プロジェクト .docsweep.yaml > グローバル ~/.docsweep/config.yaml > 内蔵 DEFAULT」の
    重なりを説明しており固有情報を含まないため、グローバル注入・プロジェクト注入のどちらでも同文で効く。
    """
    if lang == "en":
        return "\n".join([
            "### Assigning a due date (`due:`)",
            "",
            "When creating a new `plan_*.md` / `pending_*.md`, add `due: YYYY-MM-DD` to the frontmatter.",
            "Compute the date as \"today + N days\" from `due.default_offset_days` in `.docsweep.yaml`",
            "(falling back to the same setting in ~/.docsweep/config.yaml, then the built-in DEFAULT:",
            "`plan=7` / `pending=14`).",
            f"To skip computing it by hand, `{docsweep_command('new', '<type>', '<topic>')}` assigns it automatically",
            f"(set it explicitly with `{docsweep_command('new', '<type>', '<topic>', '--due', 'YYYY-MM-DD')}`).",
            "Do not add `due:` to a brand-new `bugfix_*.md` (it is added when the file transitions to watching).",
            "For project-specific due dates, edit `due.default_offset_days` in `.docsweep.yaml`",
            "(only the keys you write override the shared defaults = partial override).",
        ])
    return "\n".join([
        "### 対応期日（`due:`）の付け方",
        "",
        "新規 `plan_*.md` / `pending_*.md` を作る時は frontmatter に `due: YYYY-MM-DD` を入れる。",
        "日付は `.docsweep.yaml` の `due.default_offset_days`（無ければ ~/.docsweep/config.yaml の同設定、",
        "それも無ければ内蔵 DEFAULT: `plan=7` / `pending=14`）から「今日 + N 日」で計算する。",
        f"手で計算したくなければ `{docsweep_command('new', '<type>', '<topic>')}` を使えば自動で付く",
        f"（明示したい時は `{docsweep_command('new', '<type>', '<topic>', '--due', 'YYYY-MM-DD')}`）。",
        "`bugfix_*.md` は新規時には `due:` を付けない（`[様子見]` 遷移時に追記する設計）。",
        "プロジェクト固有の期日が必要なら `.docsweep.yaml` の `due.default_offset_days` を編集する",
        "（プロジェクトで書いたキーだけが全体既定を上書きする＝部分上書き可）。",
    ])


def generate_okf_block(lang: str = "ja") -> str:
    """新規 md 作成ルール（OKF frontmatter の注入経路）節を生成する（プロジェクト非依存）。

    OKF frontmatter を注入する経路は ``docsweep new``（templates_gen）だけなので、
    AI が Write 等で手書きすると ``due:`` だけの最小 frontmatter になり OKF が欠落する
    （2026-07-04 に many-ai-cli で実発生）。導線側で「原則 new を使う / 手書き時は
    OKF 一式を必ず入れる」を宣言して穴を塞ぐ。many-ai-cli 等の特定ツールには依存しない。
    """
    new_cmd = docsweep_command("new", "<type>", "<topic>")
    migrate_cmd = docsweep_command("migrate-frontmatter", "--apply")
    if lang == "en":
        return "\n".join([
            "### Creating new docs (OKF frontmatter is required)",
            "",
            f"Create new `plan_*.md` / `bugfix_*.md` / `pending_*.md` with `{new_cmd}` by default.",
            "It injects OKF (Open Knowledge Format) compatible frontmatter automatically",
            "(`type` / `status` / `tags` / `owner` / `review_status` / `related` / `last_reviewed`, plus `due`).",
            "If you (an AI agent) hand-write the file instead, do NOT emit a due-only minimal frontmatter:",
            "always include the same OKF field set (`type: plan|bugfix|pending`, `status: planned` for plan /",
            "`in-progress` for bugfix / `pending` for pending, `tags: []`, `owner: `, `review_status: draft`,",
            "`related: []`, `last_reviewed: <today>`).",
            f"To retrofit existing frontmatter-less docs in bulk, run `{migrate_cmd}`.",
            "",
            "`new` resolves the project root by walking up from cwd for a `.git` (or other project marker) "
            "when `--project-dir` is omitted, so calling it from a repo subdirectory (e.g. `web/`) still "
            "places the doc under the repo's `docs/local/`. Pass `--project-dir` explicitly only for the "
            "rare case where the detected root is not the one you want (e.g. nested git repos).",
        ])
    return "\n".join([
        "### 新規 md の作成（OKF frontmatter 必須）",
        "",
        f"新規 `plan_*.md` / `bugfix_*.md` / `pending_*.md` は原則 `{new_cmd}` で作る。",
        "OKF（Open Knowledge Format）互換の frontmatter",
        "（`type` / `status` / `tags` / `owner` / `review_status` / `related` / `last_reviewed` と `due`）が自動注入される。",
        "AI が Write 等で手書きする場合も、`due:` だけの最小 frontmatter にせず、同じ OKF フィールド一式を必ず入れること",
        "（`type: plan|bugfix|pending`、`status:` は plan=`planned` / bugfix=`in-progress` / pending=`pending`、",
        "`tags: []` / `owner: ` / `review_status: draft` / `related: []` / `last_reviewed: <今日>`）。",
        f"frontmatter 無しの既存 md を一括変換したい時は `{migrate_cmd}` を使う。",
        "",
        "`--project-dir` を省略した場合、`new` は cwd から `.git` 等の project marker を上へ遡ってプロジェクトルートを自動検出する。"
        "リポジトリのサブディレクトリ（例: `web/`）から呼んでも、そのリポジトリの `docs/local/` に正しく生成される。"
        "検出されたルートが意図と異なる場合（ネストした git リポジトリ等の特殊ケース）のみ `--project-dir` を明示する。",
    ])


def generate_guidance_block(lang: str = "ja") -> str:
    """セッション開始時に brief を読む導線＋ due ルール（プロジェクト非依存・グローバル注入可）。

    文言は常に同じなので、グローバル（~/.claude/CLAUDE.md 等）に一度入れれば全プロジェクトで効く。
    due ルールもプロジェクト非依存（generate_due_block 参照）のためここに同梱する。
    グローバルに寄せたくない場合はプロジェクト inject（include_guidance=True 既定）で同じ内容が入る。
    """
    brief_cmd = docsweep_command("brief")
    cross_cmd = docsweep_command("cross")
    if lang == "en":
        return "\n".join([
            "## docsweep — check remaining work at session start (required)",
            "",
            f"Before starting any work, run `{brief_cmd}` (or the `brief` tool when connected via MCP)",
            "to check today's single pick. `brief` decisively returns the highest-scoring item for the",
            "cwd project. Prefer this `python -m docsweep` form even if no `docsweep` command is on PATH.",
            "",
            "When the user says \"continue\" / \"pick up today's work\", target `today_pick.path` from `brief`.",
            f"To work across multiple projects, use `{cross_cmd}` or MCP `cross()`.",
            "",
            "### Choosing a route (all AI tools)",
            "",
            "- Morning entry point (high value for natural-language launch): MCP `brief` / `cross` / `capture_extract` / `capture_save`",
            "- Everything else (consistency checks, archive resurrection, graphs, etc.): `docsweep <command> --json` via shell",
            "- In Claude Code, the `/D` slash command also dispatches all three routes",
            "",
            generate_okf_block(lang),
            "",
            generate_due_block(lang),
        ])
    return "\n".join([
        "## docsweep — セッション開始時の残作業確認（必須）",
        "",
        f"作業を始める前に、まず `{brief_cmd}`（MCP 接続時は `brief` ツール）を実行して",
        "今日の 1 個を確認すること。`brief` は cwd プロジェクトの最高スコア 1 件を断定して返す。",
        "PATH に `docsweep` コマンドが無くても、この `python -m docsweep` 形式を優先すること。",
        "",
        "ユーザーが「続きやって」「今日の続き」と言ったら、`brief` の `today_pick.path` を対象にする。",
        f"複数プロジェクトを横断したい時は `{cross_cmd}` か MCP `cross()` を使う。",
        "",
        "### 経路選択（全 AI 対応）",
        "",
        "- 朝の入口（自然言語起動の価値が高い）: MCP `brief` / `cross` / `capture_extract` / `capture_save`",
        "- それ以外（整合チェック・archive 蘇生・グラフ等）: Bash で `docsweep <command> --json`",
        "- Claude Code では `/D` slash command でも 3 経路をまとめてディスパッチできる",
        "",
        generate_okf_block(lang),
        "",
        generate_due_block(lang),
    ])


def generate_managed_block(
    sm: StateModel, lang: str = "ja", *, use_frontmatter: bool = False, include_guidance: bool = True
) -> str:
    """プロジェクト用の管理ブロック本文（ラベル節＋任意で導線）。

    導線をグローバルへ寄せている場合は ``include_guidance=False`` でラベル節だけにできる（二重化回避）。
    """
    block = generate_label_block(sm, lang, use_frontmatter=use_frontmatter)
    if include_guidance:
        block = block + "\n\n" + generate_guidance_block(lang)
    return block


# プロジェクトの各ターゲットへ書く inner（CLAUDE.md=正本 / AGENTS.md 等=ポインタ）。inject と preview で共有。
def _pointer_body(lang: str) -> str:
    if lang == "en":
        return (
            "For docsweep operation rules (status labels and the remaining-work briefing), "
            "see the docsweep managed block in CLAUDE.md."
        )
    return "docsweep の運用ルール（ステータスラベル・残作業導線）は CLAUDE.md の docsweep 管理ブロックを参照してください。"


def _project_inners(sm: StateModel, lang: str, *, use_frontmatter: bool, include_guidance: bool) -> tuple[str, str]:
    claude_inner = generate_managed_block(
        sm, lang, use_frontmatter=use_frontmatter, include_guidance=include_guidance
    )
    pointer_inner = _hook_inner(_pointer_body(lang), docsweep_command("eject"), lang)
    return claude_inner, pointer_inner


def _global_inner(agent: str, lang: str) -> str:
    """グローバル先へ書く最小フック inner。claude=@import 1 行 / その他=本文インライン。inject と preview で共有。"""
    if agent == "claude":
        return _hook_inner(f"@{GUIDANCE_IMPORT}", docsweep_command("eject", "--global"), lang)
    return _hook_inner(
        generate_guidance_block(lang),
        docsweep_command("eject", "--global", "--agent", agent),
        lang,
    )


def _wrap(inner: str) -> str:
    return f"{MARK_START}\n{inner.rstrip()}\n{MARK_END}"


def _find_block(text: str) -> tuple[int, int] | None:
    spans = _find_all_blocks(text)
    return spans[0] if spans else None


def _find_all_blocks(text: str) -> list[tuple[int, int]]:
    """管理ブロック（START..END）を全て列挙する。

    END を START の後ろから探すことで、ユーザー本文に END マーカー文字列が紛れていても
    誤判定しない。複数ブロックがあっても 2 個目以降を取りこぼさない。
    """
    spans: list[tuple[int, int]] = []
    i = 0
    while True:
        s = text.find(MARK_START, i)
        if s == -1:
            break
        e = text.find(MARK_END, s + len(MARK_START))
        if e == -1:
            break
        end = e + len(MARK_END)
        spans.append((s, end))
        i = end
    return spans


def _inner_of(text: str, span: tuple[int, int]) -> str:
    seg = text[span[0]:span[1]]
    return seg[len(MARK_START):-len(MARK_END)].strip()


def load_manifest() -> dict:
    if not MANIFEST_PATH.is_file():
        return {"projects": {}}
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"projects": {}}


def save_manifest(data: dict) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _now() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def _write_managed_file(
    path: Path, inner: str, manifest_entry: dict, result: InjectResult, *, dry_run: bool
) -> None:
    new_block = _wrap(inner)
    rel = path.name
    prev_hash = (manifest_entry.get("blocks") or {}).get(rel)

    if path.is_file():
        text = path.read_text(encoding="utf-8", errors="replace")
        spans = _find_all_blocks(text)
        if spans:
            current_inner = _inner_of(text, spans[0])
            # 手編集検出: 前回注入と現在の（先頭）ブロックが食い違うなら .bak を取る。
            if prev_hash and _block_hash(current_inner) != prev_hash:
                result.warnings.append(f"{rel}: 管理ブロックが手編集されています。.bak を作成しました。")
                if not dry_run:
                    path.with_suffix(path.suffix + ".bak").write_text(text, encoding="utf-8")
            if len(spans) > 1:
                result.warnings.append(f"{rel}: 管理ブロックが複数あります。1 つに統合しました。")
            if len(spans) == 1 and _block_hash(current_inner) == _block_hash(inner):
                result.skipped.append(rel)  # 冪等: 変化なし
                (manifest_entry.setdefault("blocks", {}))[rel] = _block_hash(inner)
                return
            # 余剰ブロックを末尾側から除去（先頭オフセットを保つ）→ 先頭を新ブロックへ置換。
            new_text = text
            for sp in reversed(spans[1:]):
                new_text = new_text[:sp[0]] + new_text[sp[1]:]
            new_text = new_text[:spans[0][0]] + new_block + new_text[spans[0][1]:]
        else:
            sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
            new_text = text + sep + new_block + "\n"
    else:
        new_text = new_block + "\n"

    if not dry_run:
        path.write_text(new_text, encoding="utf-8")
    result.written.append(rel)
    (manifest_entry.setdefault("blocks", {}))[rel] = _block_hash(inner)


def _strip_managed_blocks(
    path: Path, prev_hash: str | None, result: "EjectResult", *, dry_run: bool
) -> bool:
    """ファイルから全管理ブロックを除去する。手編集は .bak 退避。除去したら True。

    project / global の eject で共有（除去ロジックを 1 か所に集約しドリフトを防ぐ）。
    """
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8", errors="replace")
    spans = _find_all_blocks(text)
    if not spans:
        return False
    # 手編集検出（先頭ブロック基準）。
    if prev_hash and _block_hash(_inner_of(text, spans[0])) != prev_hash:
        result.warnings.append(f"{path.name}: 手編集を検出。.bak を作成しました。")
        if not dry_run:
            path.with_suffix(path.suffix + ".bak").write_text(text, encoding="utf-8")
    # 全ブロックと直前の余分な空行を末尾側から除去（オフセットずれ防止）。
    new_text = text
    for sp in reversed(spans):
        before = new_text[:sp[0]].rstrip("\n")
        after = new_text[sp[1]:].lstrip("\n")
        new_text = before + ("\n\n" if before and after else "") + after
    new_text = new_text.rstrip("\n")
    new_text = new_text + "\n" if new_text else ""
    if not dry_run:
        path.write_text(new_text, encoding="utf-8")
    return True


def inject(
    project_dir: Path,
    *,
    preset: str | None = None,
    targets: tuple[str, ...] = DEFAULT_TARGETS,
    write_yaml: bool = True,
    include_guidance: bool = True,
    lang: str | None = None,
    dry_run: bool = False,
) -> InjectResult:
    project_dir = project_dir.resolve()
    p: Preset = get_preset(preset)
    if lang and lang != p.lang:
        # 明示 --lang は preset の既定言語を上書きする（states のラベル辞書は両言語を持つ）。
        p = replace(p, lang=lang)
    sm = p.states
    result = InjectResult(project=project_dir.name)

    manifest = load_manifest()
    key = project_dir.as_posix()
    entry = manifest["projects"].get(key, {"preset": p.name, "blocks": {}, "ts": _now()})
    entry["preset"] = p.name
    entry["preset_version"] = p.version

    # CLAUDE.md = 正本（ラベル節＋導線）。AGENTS.md 等は複製せず CLAUDE.md を指すポインタにする
    # （single source of truth。Codex は AGENTS.md のポインタを読んで CLAUDE.md を参照する）。
    claude_inner, pointer_inner = _project_inners(
        sm, p.lang, use_frontmatter=p.use_frontmatter, include_guidance=include_guidance
    )

    if write_yaml:
        yaml_path = project_dir / ".docsweep.yaml"
        if not yaml_path.exists():
            content = _render_yaml(p)
            if not dry_run:
                yaml_path.write_text(content, encoding="utf-8")
            result.yaml_path = yaml_path.as_posix()
        else:
            result.skipped.append(".docsweep.yaml (既存・温存)")

    for t in targets:
        # CLAUDE.md は常に正本を書く。AGENTS.md は存在する場合のみ、CLAUDE.md を指すポインタを書く。
        path = project_dir / t
        if t != "CLAUDE.md" and not path.is_file():
            continue
        inner = claude_inner if t == "CLAUDE.md" else pointer_inner
        _write_managed_file(path, inner, entry, result, dry_run=dry_run)

    entry["ts"] = _now()
    manifest["projects"][key] = entry
    if not dry_run:
        save_manifest(manifest)
    return result


def _ensure_global_config_scaffold(lang: str = "ja", *, dry_run: bool = False) -> bool:
    """``~/.docsweep/config.yaml`` が無ければ due ひな型付きで作る。既存は触らない。

    既存ユーザー設定を上書きしないことを最優先（破壊回避）。新規に作る時のみ、
    全プロジェクト共通の既定として ``due:`` ブロックの書き方が一目で分かる scaffold を置く。
    返り値 True = 新規作成した。False = 既存があったので何もしなかった。
    """
    if GLOBAL_CONFIG_PATH.is_file():
        return False
    if lang == "en":
        header = (
            "# docsweep global settings (shared defaults for all projects).\n"
            "# A project's .docsweep.yaml partially overrides this (the project wins).\n\n"
        )
    else:
        header = (
            "# docsweep グローバル設定（全プロジェクト共通の既定）。\n"
            "# プロジェクトの .docsweep.yaml がここを部分上書きする（プロジェクトの方が強い）。\n\n"
        )
    body = header + _due_scaffold(scope="global", lang=lang)
    if not dry_run:
        GLOBAL_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        GLOBAL_CONFIG_PATH.write_text(body, encoding="utf-8")
    return True


def _due_scaffold(*, scope: str, lang: str = "ja") -> str:
    """``due:`` ブロックのコメントアウト済みひな型を返す（プロジェクト / グローバル共通）。

    既定値そのままを例示するので、コメントを外しただけでは挙動が変わらない（嘘の上書きが起きない）。
    値を編集して初めて反映される。プロジェクト > グローバル > 内蔵 DEFAULT の順で key 単位に重なる。
    """
    if lang == "en":
        if scope == "project":
            intro = (
                "# Due dates (initial offset_days for auto-assignment). To override with project-specific\n"
                "# values, uncomment and edit. Only the keys you write take precedence over the global\n"
                "# ~/.docsweep/config.yaml and the built-in DEFAULT (unwritten keys keep the upper values).\n"
            )
        else:
            intro = (
                "# Due dates (initial offset_days for auto-assignment) shared by all projects.\n"
                "# A project's .docsweep.yaml due: block overrides these per key (the project wins).\n"
            )
    elif scope == "project":
        intro = (
            "# 対応期日（自動付与の初期 offset_days）。プロジェクト固有の期日に上書きしたければ\n"
            "# コメントを外して値を書き換える。書いたキーだけがグローバル ~/.docsweep/config.yaml と\n"
            "# 内蔵 DEFAULT に対して優先される（書かなかったキーは上位の値を温存）。\n"
        )
    else:
        intro = (
            "# 対応期日（自動付与の初期 offset_days）の全プロジェクト共通の既定。\n"
            "# プロジェクト側 .docsweep.yaml の due: ブロックで個別に上書きできる（プロジェクトの方が強い）。\n"
        )
    lines = [intro, "# due:", "#   default_offset_days:"]
    for k, v in DEFAULT_DUE_OFFSET_DAYS.items():
        lines.append(f"#     {k}: {v}")
    return "\n".join(lines) + "\n"


def _render_yaml(p: Preset) -> str:
    states_block = []
    for st in p.states.states:
        labels = ", ".join(f"{k}: {v}" for k, v in st.labels.items())
        states_block.append(
            f"  - key: {st.key}\n"
            f"    labels: {{ {labels} }}\n"
            f"    archive: {str(st.archive).lower()}\n"
            f"    auto_move: {str(st.auto_move).lower()}"
        )
    header = f"# docsweep settings (preset: {p.name})" if p.lang == "en" else f"# docsweep 設定（preset: {p.name}）"
    return (
        f"{header}\n"
        f"# {p.description}\n"
        f"lang: {p.lang}\n"
        f"preset: {p.name}\n"
        f"states:\n" + "\n".join(states_block) + "\n\n"
        + _due_scaffold(scope="project", lang=p.lang)
    )


@dataclass
class EjectResult:
    project: str
    removed: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    purged_yaml: bool = False


def eject(project_dir: Path, *, purge: bool = False, dry_run: bool = False) -> EjectResult:
    """管理ブロックだけ削除。ユーザー手書きは温存。--purge で .docsweep.yaml も削除。"""
    project_dir = project_dir.resolve()
    result = EjectResult(project=project_dir.name)
    manifest = load_manifest()
    key = project_dir.as_posix()
    entry = manifest["projects"].get(key, {"blocks": {}})

    for fname in list((entry.get("blocks") or {}).keys()) or list(DEFAULT_TARGETS):
        path = project_dir / fname
        prev_hash = (entry.get("blocks") or {}).get(fname)
        if _strip_managed_blocks(path, prev_hash, result, dry_run=dry_run):
            result.removed.append(fname)

    if purge:
        yaml_path = project_dir / ".docsweep.yaml"
        if yaml_path.is_file():
            if not dry_run:
                yaml_path.unlink()
            result.purged_yaml = True

    if not dry_run:
        manifest["projects"].pop(key, None)
        save_manifest(manifest)
    return result


def inject_global(
    *, agent: str = "claude", target: str | Path | None = None, lang: str = "ja", dry_run: bool = False
) -> InjectResult:
    """導線（triage を読む行動ルール）のみを AI ツールのグローバル設定へ注入する。

    ラベル節（状態モデル）はプロジェクト固有なのでグローバルには書かない。一度入れれば全プロジェクトで効く。
    """
    path = resolve_global_target(agent, target)
    result = InjectResult(project=f"global:{agent}")
    _warn_if_shadowed(path, result, agent)

    # 中央 guidance.md は @import で参照する agent（claude）のときだけ生成する。
    # Codex 等は導線本文をインライン展開し中央ファイルを参照しないので、作ると誰も読まない
    # 孤児になる（eject 側の保持判定とも整合: guidance.md は Claude が居る時だけ保持）。
    if _agent_uses_central(agent):
        write_guidance_file(lang, dry_run=dry_run)
    # docsweep 自身のグローバル設定 (~/.docsweep/config.yaml) のひな型を「未存在のときだけ」作る。
    # 既存ユーザー設定には触らない。due.default_offset_days を全プロジェクト共通の既定として
    # ここに書いてもらえるよう、コメントアウト済みのブロックを提示する。
    if _ensure_global_config_scaffold(lang, dry_run=dry_run):
        if lang == "en":
            result.warnings.append(
                "~/.docsweep/config.yaml did not exist, so a scaffold was created"
                " (edit the due block to set shared defaults)."
            )
        else:
            result.warnings.append(
                "~/.docsweep/config.yaml が無かったのでひな型を作成しました（due ブロックを編集すると全体既定になります）。"
            )
    inner = _global_inner(agent, lang)

    manifest = load_manifest()
    key = path.as_posix()
    entry = manifest["projects"].get(key, {"scope": "global", "agent": agent, "blocks": {}, "ts": _now()})
    entry["scope"] = "global"
    entry["agent"] = agent
    entry["guidance_version"] = GUIDANCE_VERSION

    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
    _write_managed_file(path, inner, entry, result, dry_run=dry_run)

    entry["ts"] = _now()
    manifest["projects"][key] = entry
    if not dry_run:
        save_manifest(manifest)
    return result


def eject_global(
    *, agent: str = "claude", target: str | Path | None = None, dry_run: bool = False
) -> EjectResult:
    """グローバルへ注入した導線ブロックを剥がす（project eject と除去ロジックを共有）。"""
    path = resolve_global_target(agent, target)
    result = EjectResult(project=f"global:{agent}")
    manifest = load_manifest()
    key = path.as_posix()
    entry = manifest["projects"].get(key, {"blocks": {}})
    prev_hash = (entry.get("blocks") or {}).get(path.name)
    if _strip_managed_blocks(path, prev_hash, result, dry_run=dry_run):
        result.removed.append(path.name)
    if not dry_run:
        manifest["projects"].pop(key, None)
        # 中央 guidance.md を @import 参照する global（=claude）が他に残っていなければ撤去する。
        # Codex はインライン展開で guidance.md を参照しないので、残っていても保持理由にならない。
        still_referenced = any(
            v.get("scope") == "global" and _agent_uses_central(v.get("agent"))
            for v in manifest["projects"].values()
        )
        if not still_referenced and GUIDANCE_PATH.is_file():
            GUIDANCE_PATH.unlink()
            result.removed.append(GUIDANCE_PATH.name)
        save_manifest(manifest)
    return result


def list_injected() -> list[dict]:
    manifest = load_manifest()
    items = []
    for k, v in manifest.get("projects", {}).items():
        scope = v.get("scope", "project")
        # scope=project は preset_version、scope=global は guidance_version を共通の "version" として返す
        # （UI 側は scope を見ずに version 列を描画できる）。古いマニフェストで欠けていれば None。
        version = v.get("preset_version") if scope == "project" else v.get("guidance_version")
        items.append({
            "project": Path(k).name,
            "path": k,
            "preset": v.get("preset"),
            "scope": scope,
            "agent": v.get("agent"),
            "ts": v.get("ts"),
            "version": version,
        })
    return items


def preview_inject(
    project_dir: Path, *, preset: str | None = None, include_guidance: bool = True, lang: str | None = None
) -> dict:
    """プロジェクト inject で「何が書かれるか」を返す（書き込みはしない・UI の dry-run プレビュー用）。"""
    project_dir = Path(project_dir).resolve()
    p: Preset = get_preset(preset)
    claude_inner, pointer_inner = _project_inners(
        p.states, lang or p.lang, use_frontmatter=p.use_frontmatter, include_guidance=include_guidance
    )
    blocks = [{"file": "CLAUDE.md", "text": _wrap(claude_inner)}]
    if (project_dir / "AGENTS.md").is_file():
        blocks.append({"file": "AGENTS.md", "text": _wrap(pointer_inner)})
    return {
        "scope": "project",
        "project": project_dir.name,
        "path": project_dir.as_posix(),
        "blocks": blocks,
        "yaml_exists": (project_dir / ".docsweep.yaml").is_file(),
    }


def preview_global(*, agent: str = "claude", target: str | Path | None = None, lang: str = "ja") -> dict:
    """グローバル inject で「何が書かれるか」を返す（書き込みはしない・UI の dry-run プレビュー用）。"""
    path = resolve_global_target(agent, target)
    probe = InjectResult(project=f"global:{agent}")
    _warn_if_shadowed(path, probe, agent)
    # 中央ファイルは @import 参照する agent（claude）でのみ生成・参照される。Codex 等は
    # 導線をインライン展開するので、プレビューでも中央ファイルの行を見せない（誤誘導を防ぐ）。
    uses_central = _agent_uses_central(agent)
    return {
        "scope": "global",
        "agent": agent,
        "path": path.as_posix(),
        "blocks": [{"file": path.name, "text": _wrap(_global_inner(agent, lang))}],
        "guidance_path": GUIDANCE_PATH.as_posix() if uses_central else None,
        "guidance": generate_guidance_block(lang) if uses_central else None,
        "warnings": probe.warnings,
    }
